### ISSUE TITLE
how to add METADATA on windows?

### ISSUE THREAD

**Issue by xkungfu** [yasirfaizahmed/twitter_automation#5]
```
(env) I:\PYTHONWORK2022\twitterauto\twitter_automation>python test.py
2023-05-13 18:33:26,303 - TA - INFO - Logger Initilized, logging to the stdout and to I:\PYTHONWORK2022\twitterauto\twitter_automation\_LOGs\May-13-2023_18-33-26.log

DevTools listening on ws://127.0.0.1:62683/devtools/browser/feb2d51a-4219-4760-8fd5-b48baaa51b00
Traceback (most recent call last):
  File "I:\PYTHONWORK2022\twitterauto\twitter_automation\test.py", line 27, in <module>
    ReportProfile(user_profile='https://twitter.com/NoreenGul17', report_category='')()
  File "I:\PYTHONWORK2022\twitterauto\twitter_automation\base\base_step.py", line 25, in __call__
    self.main()
  File "I:\PYTHONWORK2022\twitterauto\twitter_automation\base\base_step.py", line 19, in main
    self.Do()
  File "I:\PYTHONWORK2022\twitterauto\twitter_automation\steps\Selenium\selenium_steps.py", line 283, in Do
    _bmd = BotMetadata()
  File "I:\PYTHONWORK2022\twitterauto\twitter_automation\patterns\patterns.py", line 13, in __call__
    cls.instances[cls].__init__(*args, **kwargs)
  File "I:\PYTHONWORK2022\twitterauto\twitter_automation\scripts\scripts_config.py", line 12, in __init__
    __file_path = os.environ['METADATA']
  File "D:\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'METADATA'
```

run on windows, this is error report.

how to add METADATA on windows?

-------------------------------------------------------------------

I added METADATA =I:\Temp

the new error is:

```
  File "I:\PYTHONWORK2022\twitterauto\twitter_automation\scripts\scripts_config.py", line 19, in __init__
    __file = open(__file_path)
PermissionError: [Errno 13] Permission denied: 'I:\\Temp'
```

what is the right path for METADATA?

**Comment by yasirfaizahmed** [comment]
> ```
> (env) I:\PYTHONWORK2022\twitterauto\twitter_automation>python test.py
> 2023-05-13 18:33:26,303 - TA - INFO - Logger Initilized, logging to the stdout and to I:\PYTHONWORK2022\twitterauto\twitter_automation\_LOGs\May-13-2023_18-33-26.log
> 
> DevTools listening on ws://127.0.0.1:62683/devtools/browser/feb2d51a-4219-4760-8fd5-b48baaa51b00
> Traceback (most recent call last):
>   File "I:\PYTHONWORK2022\twitterauto\twitter_automation\test.py", line 27, in <module>
>     ReportProfile(user_profile='https://twitter.com/NoreenGul17', report_category='')()
>   File "I:\PYTHONWORK2022\twitterauto\twitter_automation\base\base_step.py", line 25, in __call__
>     self.main()
>   File "I:\PYTHONWORK2022\twitterauto\twitter_automation\base\base_step.py", line 19, in main
>     self.Do()
>   File "I:\PYTHONWORK2022\twitterauto\twitter_automation\steps\Selenium\selenium_steps.py", line 283, in Do
>     _bmd = BotMetadata()
>   File "I:\PYTHONWORK2022\twitterauto\twitter_automation\patterns\patterns.py", line 13, in __call__
>     cls.instances[cls].__init__(*args, **kwargs)
>   File "I:\PYTHONWORK2022\twitterauto\twitter_automation\scripts\scripts_config.py", line 12, in __init__
>     __file_path = os.environ['METADATA']
>   File "D:\Python39\lib\os.py", line 679, in __getitem__
>     raise KeyError(key) from None
> KeyError: 'METADATA'
> ```
> 
> run on windows, this is error report.
> 
> how to add METADATA on windows?
> 
> I added METADATA =I:\Temp
> 
> the new error is:
> 
> ```
>   File "I:\PYTHONWORK2022\twitterauto\twitter_automation\scripts\scripts_config.py", line 19, in __init__
>     __file = open(__file_path)
> PermissionError: [Errno 13] Permission denied: 'I:\\Temp'
> ```
> 
> what is the right path for METADATA?

METADATA is just a environment variable you have to set so that the script can access it in run time, 
METADATA is a .json file containing info about a twitter user (a dummy one) so that you can use this dummy profile as a bot
heres an example how this file must look like, 

    {
      "bot1": {
        "EMAIL_KEY": "yourbotsmailid@botmail.com",
        "USERNAME_KEY": "twitterhandle",
        "PASSWORD_KEY": "twittrpassowrd"
      }
    }


setting an environment variable in windows is a bit pain, I would suggest you to use linux VM or get on on google-cloud-VM 
this project was never made to work on windows, never test on it as well .

**Comment by xkungfu** [comment]
got it. thank you very much!
