### ISSUE TITLE
can you add a screenshot command what can run on windows?

### ISSUE THREAD

**Issue by xkungfu** [yasirfaizahmed/twitter_automation#7]
I found the the scripts get icon coord  from the screenshot images. but on windows there is no the command scrot.

so, is there a solution about screenshot on windows?

thank you!

**Comment by yasirfaizahmed** [comment]
I'm unaware of any such tools similar to `scrot` on windows, but you can try 
`nircmd screenshot screenshot.bmp`

if that does'nt work then you can try with python `PIL` package as below,

```
import PIL.ImageGrab

img = PIL.ImageGrab.grab()
img.save('screenshot.bmp')
```

**Comment by xkungfu** [comment]
I have moved the scripts to UBUNTU. 
thank you very much.
